apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip-access-ingress
  namespace: z-grid
  labels:
    app: z-grid-monitoring-dashboard
    component: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      listen 80;
      server_name _;
spec:
  defaultBackend:
    service:
      name: emergency-monitoring-dashboard-service
      port:
        number: 5000