apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-test-monitor-ingress
  namespace: z-grid
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: load-test-monitor.20.242.183.197.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: load-test-monitor-service
            port:
              number: 80